/*

 PLAYER.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char player[] =
{
  0x1C,0x3C,0x4E,0x7E,0x38,0x04,0x46,0x7E,
  0x5E,0x7E,0x7A,0x3C,0x00,0x3C,0x00,0x24,
  0x38,0x3C,0x72,0x7E,0x1C,0x20,0x62,0x7E,
  0x7A,0x7E,0x5E,0x3C,0x00,0x3C,0x00,0x24
};

/* End of PLAYER.C */
