/*

 SMILE_GLASS16.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __smile_glass16_h_INCLUDE
#define __smile_glass16_h_INCLUDE

/* Bank of tiles. */
#define smile_glass16Bank 0
/* Start of tile array. */
extern const unsigned char smile_glass16[];

#endif

/* End of SMILE_GLASS16.H */
