/*

 MAP_LVL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 11
   Tile set      : map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 11
#define mapHeight 11
#define mapBank 0

extern unsigned char map[];

/* End of MAP_LVL2.H */
